Repository heroku/buildpacks-python, pull requests merged in 2025-04, with the labels that each got.

#346 Update repo metadata
  .github/CODEOWNERS
Labels: skip changelog

#351 Add some more unit tests
  src/checks.rs
  src/python_version.rs
  src/utils.rs
Labels: skip changelog

#352 Remove support for `runtime.txt`
  CHANGELOG.md
  src/errors.rs
  src/main.rs
  src/python_version.rs
  src/runtime_txt.rs
  tests/fixtures/pip_oldest_python/.python-version
  tests/fixtures/pip_oldest_python/requirements.txt
  tests/pip_test.rs
  tests/python_version_test.rs
Labels: semver: major

#355 Improve the error messages for file I/O errors
  CHANGELOG.md
  src/detect.rs
  src/django.rs
  src/errors.rs
  src/layers/pip.rs
  src/layers/poetry.rs
  src/main.rs
  src/package_manager.rs
  src/python_version.rs
  src/utils.rs
  tests/python_version_test.rs
Labels: enhancement

#356 Improve the error messages for command I/O errors
  CHANGELOG.md
  src/errors.rs
  src/utils.rs
Labels: enhancement
